kube-state-metrics:
  collectors: [ ]
  extraArgs:
    - --custom-resource-state-only=true
  rbac:
    extraRules:
      - apiGroups:
          - source.toolkit.fluxcd.io
          - kustomize.toolkit.fluxcd.io
          - helm.toolkit.fluxcd.io
          - notification.toolkit.fluxcd.io
          - image.toolkit.fluxcd.io
        resources:
          - gitrepositories
          - buckets
          - helmrepositories
          - helmcharts
          - ocirepositories
          - kustomizations
          - helmreleases
          - alerts
          - providers
          - receivers
          - imagerepositories
          - imagepolicies
          - imageupdateautomations
        verbs: [ "list", "watch" ]
  customResourceState:
    enabled: true
    config:
      spec:
        resources:
          - groupVersionKind:
              group: helm.toolkit.fluxcd.io
              version: "v2beta1"
              kind: HelmRelease
            metricNamePrefix: gotk
            metrics:
              - name: "resource_info"
                help: "The current state of a GitOps Toolkit resource."
                each:
                  type: Info
                  info:
                    labelsFromPath:
                      name: [ metadata, name ]
                labelsFromPath:
                  exported_namespace: [ metadata, namespace ]
                  suspended: [ spec, suspend ]
                  ready: [ status, conditions, "[type=Ready]", status ]
              - name: "helmrelease_version_info"
                help: "The version information of helm release resource."
                each:
                  type: Info
                  info:
                    labelsFromPath:
                      version: [ status, lastAppliedRevision ]
                labelsFromPath:
                  name: [ metadata, name ]
                  exported_namespace: [ metadata, namespace ]
                  chartName: [ spec, chart, spec, chart ]
...