apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: weave-gitops-monitor
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: monitoring
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions:
      - {key: app.kubernetes.io/name, operator: In, values: [weave-gitops]}
      - {key: app.kubernetes.io/instance, operator: In, values: [ww-gitops]}
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
      podMetricsEndpoints:
        - targetPort: metrics
          selector:
            matchLabels:
              app.kubernetes.io/name: weave-gitops
              app.kubernetes.io/instance: ww-gitops
          namespaceSelector:
            matchNames:
              - flux-system
          path: /metrics