apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: weave-gitops-monitor
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: monitoring
    release: "prometheus"
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchLabels:
      app: weave-gitops
  endpoints:
  - interval: 15s
    targetPort: 8080
    path: /metrics
  relabelings:
  # https://github.com/prometheus-operator/prometheus-operator/issues/4816
    - sourceLabels: [__meta_kubernetes_pod_phase]
      action: keep
      regex: Running
