apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: weave-gitops-monitor
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: monitoring  
spec:
  selector:
    matchLabels:
      name: weave-gitops
  endpoints:
    - port: "8080"
      path: /metrics