apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: weave-gitops-monitor
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: monitoring
    release: "prometheus"
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions:
      - {key: app.kubernetes.io/name, operator: In, values: [weave-gitops]}
      - {key: app.kubernetes.io/instance, operator: In, values: [ww-gitops]}
  endpoints:
  - interval: 15s
    targetPort: 8080
    path: /metrics
